### PR TITLE
add fr_address_book_for_woocommerce_address_fields filter

### PR DESCRIPTION
**Pull request by iwillhappy1314**
Add `fr_address_book_for_woocommerce_address_fields ` filter to allow farther customization.

use case:

```
add_filter('fr_address_book_for_woocommerce_address_fields', function ($fields, $address_id, $saved_addresses)
{
    $state_code = $saved_addresses[ $address_id ][ 'state' ];
    $city_name  = $saved_addresses[ $address_id ][ 'city' ];
    $area_name  = $saved_addresses[ $address_id ][ 'address_1' ];

    $cities = Helper::get_state_cities($state_code);
    $cities = wp_list_pluck($cities, 'name', 'name');

    $areas = Helper::get_city_areas($state_code, $city_name);
    $areas = wp_list_pluck($areas, 'name', 'name');

    $fields[ 'billing_city' ][ 'options' ]                             = $cities;
    $fields[ 'billing_city' ][ 'custom_attributes' ][ 'data-default' ] = $city_name;

    $fields[ 'billing_address_1' ][ 'options' ]                             = $areas;
    $fields[ 'billing_address_1' ][ 'custom_attributes' ][ 'data-default' ] = $area_name;

    return $fields;
}, 10, 3);
```

### CODE REVIEW

**Comment by iwillhappy1314** [comment]
#3

**Comment by fahrirusliyadi** [comment]
Thanks for the PR. 

I personally prefer `woocommerce_default_address_fields` to customize the fields. Because the fields are not only used in edit address form, but also in add address form and checkout form; and `woocommerce_default_address_fields` covers all. But your PR only covers the  edit address form.

Or maybe you have a case where `woocommerce_default_address_fields` can't provide a solution?

**Comment by iwillhappy1314** [comment]
Yes, I know the `woocommerce_default_address_fields` filter, but when I need to change the fields modified by your plugin, can`t done with the `woocommerce_default_address_fields` filter.

**Comment by fahrirusliyadi** [comment]
What do you mean? This plugin does not modify any fields. Could you point it to me, or maybe an example?

Sorry for the late reply, I've been very busy.

**Comment by iwillhappy1314** [comment]
At this line: https://github.com/fahrirusliyadi/fr-address-book-for-woocommerce/blob/cf2de82c51b8f26d00ae402b5ba6ad06b34c1a48/src/Fr_Address_Book_for_WooCommerce_Frontend_MyAccount_AddressBookEdit.php#L43

if I want to change the value set by your plugin, I need the filter in the pull request.

**Comment by fahrirusliyadi** [comment]
I see. So, not only you want to modify the field definitions, but also the field values.

In my opinion, you can use `woocommerce_default_address_fields` to modify the field definitions. 

To modify the field value, we can create a new filter on `Fr_Address_Book_for_WooCommerce_Customer->get_addresses` method instead, because it is called everywhere. We shouldn't add it to `Fr_Address_Book_for_WooCommerce_Frontend_MyAccount_AddressBookEdit->display_endpoint_content` method, because it's only called on edit address form.

What do you think?

**Pull request closed without merging**
